"""add start_date to projects

Revision ID: 18f2e6b8d296
Revises: 43395bc82cc3
Create Date: 2026-02-25 13:13:07.334266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18f2e6b8d296'
down_revision = '43395bc82cc3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('start_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'start_date')
    # ### end Alembic commands ###
