"""Initial schema with users, projects, issues, and comments

Revision ID: 43395bc82cc3
Revises: 
Create Date: 2026-02-18 19:36:05.504609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43395bc82cc3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
